services:
  django:
    container_name: django
    image: ghcr.io/akim-13/cleaning-website:latest
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    volumes:
      - static:/var/www/static
      - media:/var/www/media
    depends_on:
      - postgres
      - redis
      - logstash
    env_file:
      - .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5044"
    networks:
      - elk

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - logstash
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5044"
    networks:
      - elk

        redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    depends_on:
      - logstash
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5044"
    networks:
      - elk

  nginx:
    container_name: nginx
    image: nginx:1.27
    ports:
      - "80:80"                # HTTP requests
      - "443:443"              # HTTPS requests
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      # Uncomment for initial deployment.
      #- ./nginx/nginx.initial.conf:/etc/nginx/conf.d/default.conf
      - static:/var/www/static
      - media:/var/www/media
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    depends_on:
      - django
      - certbot
      - logstash
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5044"
    networks:
      - elk

  certbot:
    container_name: certbot
    image: certbot/certbot
    entrypoint: ["certbot", "renew", "--webroot", "--webroot-path=/var/www/certbot"]
    # Uncomment for initial deployment.
    #entrypoint: ["certbot", "certonly", "--webroot", "--webroot-path=/var/www/certbot", "--email", "ak.reg@tuta.io", "--agree-tos", "--no-eff-email", "-d", "clean-check.ru", "-d", "www.clean-check.ru"]
    volumes:
      - certbot_etc:/etc/letsencrypt   # Persist and share with nginx
      - certbot_var:/var/www/certbot   # Persist and share with nginx
    depends_on:
      - logstash
    logging:
      driver: "gelf"

      logstash:
    container_name: logstash
    image: logstash:8.15.1
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline # Logstash pipelines
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044/udp"  # For receiving logs from Docker containers
    networks:
      - elk

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - logs:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    container_name: kibana
    image: kibana:8.15.1
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Communicate with Elasticsearch via the elk network
    ports:
      - "5601:5601"  # For port forwarding to local machine
    networks:
      - elk

# These are needed either for sharing data between different containers
# or making the data persistent (like for postgres_data).
volumes:
  logs:
  media:
  static:
  certbot_etc:
  certbot_var:
  postgres_data:

networks:
  elk:
    driver: bridge
