# Generated by Django 5.0.7 on 2024-07-15 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=255)),
                ('mark_range_min', models.SmallIntegerField(default=0)),
                ('mark_range_max', models.SmallIntegerField(default=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('location', models.ManyToManyField(to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones_created', to='main.user')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField()),
                ('confirmation', models.BooleanField()),
                ('customer_comment', models.TextField()),
                ('customer_comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_comment_photo', models.ImageField(blank=True, null=True, upload_to='./media/customer_photos/')),
                ('contractor_comment', models.TextField()),
                ('contractor_comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor_comment_photo', models.ImageField(blank=True, null=True, upload_to='./media/contractor_photos/')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.criterion')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.user')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zone')),
            ],
        ),
    ]
