# Generated by Django 5.1.1 on 2024-09-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='zone',
        ),
        migrations.AlterField(
            model_name='comment',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.sector', verbose_name='Сектор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.sector', verbose_name='Сектор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название сектора'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='operation_criteria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Операция/Критерий оценивания'),
        ),
    ]
