# Generated by Django 5.0.7 on 2024-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager_contractor', 'Менеджер Исполнитель'), ('manager_customer', 'Менеджер Заказчик'), ('representative_customer', 'Руководитель Объекта'), ('representative_contractor', 'Руководитель Клининга'), ('admin_account', 'Админ Аккаунт')], default='manager_customer', max_length=55),
        ),
    ]
