# Generated by Django 5.1.1 on 2024-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='operation_criteria',
            field=models.CharField(default=1, max_length=255, verbose_name='Операция/Критерий'),
            preserve_default=False,
        ),
    ]
