# Generated by Django 5.0.7 on 2024-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cell_contractor_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='criterion',
        ),
        migrations.AddField(
            model_name='location',
            name='mark_range_max',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='location',
            name='mark_range_min',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Criterion',
        ),
    ]
