# Generated by Django 5.0.7 on 2024-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_confirmation_mark_delete_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
