# Generated by Django 5.0.7 on 2024-08-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comment_last_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='zone_name',
            new_name='name',
        ),
    ]
