# Generated by Django 5.1.1 on 2024-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sector_operation_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='operation_criteria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Операция/Критерий'),
        ),
    ]
