# Generated by Django 5.1.1 on 2024-09-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sector_operation_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='main.location', verbose_name='Объект'),
        ),
    ]
