# Generated by Django 5.0.7 on 2024-08-14 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_location_name_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='creation_datetime',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='timestamp',
            new_name='creation_datetime',
        ),
        migrations.AddField(
            model_name='comment',
            name='submission_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mark',
            name='submission_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
