# Generated by Django 5.1.1 on 2024-09-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_zone_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='main.location', verbose_name='Объект'),
        ),
    ]
