# Generated by Django 5.0.7 on 2024-08-19 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0005_location_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.location', verbose_name='Объекты'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager_contractor', 'Менеджер Исполнитель'), ('manager_customer', 'Менеджер Заказчик'), ('representative_customer', 'Руководитель Объекта'), ('representative_contractor', 'Руководитель Клининга')], default='manager_customer', max_length=55, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BooleanField(default=False, verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='allocated_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_made_by_customer_not_contractor',
            field=models.BooleanField(verbose_name='Это сделано Заказчиком, а не Исполнителем'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.location', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./attachments/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='submission_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последение изменение'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.zone', verbose_name='Зона'),
        ),
        migrations.AlterField(
            model_name='location',
            name='mark_range_max',
            field=models.SmallIntegerField(default=5, verbose_name='Максимальная оценка'),
        ),
        migrations.AlterField(
            model_name='location',
            name='mark_range_min',
            field=models.SmallIntegerField(default=0, verbose_name='Минимальная оценка'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.location', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='submission_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последние изменение'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.zone', verbose_name='Зона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Роли к которым принадлежит пользователь.', related_name='custom_user_set', to='auth.group', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Специальные возможности пользователя.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='Возможности пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='main.location', verbose_name='Объект'),
        ),
    ]
