# Generated by Django 5.1.1 on 2024-09-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_zone_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.zone', verbose_name='Зона'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.zone', verbose_name='Зона'),
        ),
    ]
