# Generated by Django 5.0.7 on 2024-08-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_location_user_role_user_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
