# Generated by Django 5.1.1 on 2024-09-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_zone_alter_mark_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='operation_criteria',
        ),
        migrations.AlterField(
            model_name='comment',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.zone', verbose_name='Зона'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.zone', verbose_name='Зона'),
        ),
    ]
