# Generated by Django 5.0.7 on 2024-08-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_user_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager_contractor', 'Менеджер Исполнитель'), ('manager_customer', 'Менеджер Заказчик'), ('representative_customer', 'Руководитель Объекта'), ('representative_contractor', 'Руководитель Клининга'), ('admin_account', 'Админ Аккаунт')], default='manager_customer', max_length=55, verbose_name='Роль'),
        ),
    ]
