# Generated by Django 5.0.7 on 2024-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_comment_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.SmallIntegerField(verbose_name='Оценка'),
        ),
    ]
