name: Build and deploy Docker image

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        # WARNING: GHCR Personal Access Token expires! Recreate every 90 days.
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          PREFIX=ghcr.io/${{ github.repository }}
          docker buildx build -t $PREFIX:${{ github.sha }} -t $PREFIX:latest --push .
          echo "Image built and pushed with tags: ${{ github.sha }} and latest"

  deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Add SSH key for deployment
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Deploy to the server
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
              cd /mnt/data/cleaning-website
              git checkout production
              git pull --strategy-option theirs
              docker compose -f docker-compose.prod.yml pull django
              docker compose -f docker-compose.prod.yml down
              docker compose -f docker-compose.prod.yml up -d
            EOF
